package com.hopeful117.devlogai.observation.entity;

public enum ObservationType {
    ASYNCHRONOUS_COMMUNICATION,
    HTTP_SERVICE_COMMUNICATION,
    ARCHITECTURE_MODULARIZATION,
    AUTHENTICATION_LAYER,
    TEST_COVERAGE_DECREASE,
    CONTAINERIZED_PROJECT,
    SPRING_BOOT_REST_APPLICATION,
    ARCHITECTURE_DOCUMENTATION_PRESENT,
    AUTOMATED_TEST_SUITE_PRESENT,
    INTEGRATION_TEST_SUITE_PRESENT,
    MULTI_MODULE_BUILD,
    OTHER
}
