package com.hopeful117.devlogai.shared.response;

public enum ApiErrorCode {
    ROUTE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    INVALID_PARAMETER,
    MALFORMED_REQUEST,
    VALIDATION_FAILED,
    INVALID_AI_TASK_RESULT,
    ENTITY_NOT_FOUND,
    RESOURCE_CONFLICT,
    PROJECT_SLUG_ALREADY_EXISTS,
    UNSUPPORTED_ANALYSIS_TYPE,
    INTERNAL_ERROR
}
