package com.hopeful117.devlogai.profile.model;

public enum ProfileCategory {
    IDENTITY, TECHNOLOGIES, ARCHITECTURE, BUILD, API, PERSISTENCE,
    SECURITY, TESTING, DOCUMENTATION, INFRASTRUCTURE, CI_CD, QUALITY
}
