from collections import deque
from collections.abc import Iterable
from datetime import datetime, timezone
import json
from typing import Any

from pydantic import BaseModel

from app.providers.base import Prompt, ProviderGenerationResult, StructuredOutput


class MockLlmProvider:
    """Deterministic provider used by default without external credentials."""

    def __init__(self, outputs: Iterable[Any] | None = None) -> None:
        self._outputs = deque(outputs or [])
        self.requests: list[Prompt] = []

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def model_identifier(self) -> str:
        return "deterministic-v1"

    async def generate_structured(
        self,
        request: Prompt,
        response_model: type[StructuredOutput],
    ) -> StructuredOutput:
        self.requests.append(request)
        raw_output: Any
        if self._outputs:
            raw_output = self._outputs.popleft()
        elif response_model.__name__ == "DeliverableGenerationOutput":
            raw_output = {
                "title": "Deterministic mock deliverable",
                "content": "This deliverable was generated by the deterministic Mock provider from validated Insights.",
            }
        else:
            raw_output = {"proposals": []}

        if isinstance(raw_output, BaseModel):
            raw_output = raw_output.model_dump()
        return response_model.model_validate(raw_output)

    async def generate_structured_with_trace(
        self, request: Prompt, response_model: type[StructuredOutput]
    ) -> ProviderGenerationResult:
        started_at = datetime.now(timezone.utc)
        output = await self.generate_structured(request, response_model)
        completed_at = datetime.now(timezone.utc)
        return ProviderGenerationResult(
            output=output,
            raw_output=json.dumps(output.model_dump(mode="json"), sort_keys=True),
            started_at=started_at,
            completed_at=completed_at,
            input_tokens=None,
            output_tokens=None,
            total_tokens=None,
        )
