from enum import Enum


class AiTaskType(str, Enum):
    DECISION_PROPOSAL_GENERATION = "DECISION_PROPOSAL_GENERATION"
    EVENT_PROPOSAL_GENERATION = "EVENT_PROPOSAL_GENERATION"
    INSIGHT_GENERATION = "INSIGHT_GENERATION"
    DOCUMENTATION_GENERATION = "DOCUMENTATION_GENERATION"
    CHALLENGE_PROPOSAL_GENERATION = "CHALLENGE_PROPOSAL_GENERATION"
