from enum import Enum


class InsightType(str, Enum):
    PROJECT_PRESENTATION = "PROJECT_PRESENTATION"
    ARCHITECTURE_DESCRIPTION = "ARCHITECTURE_DESCRIPTION"
    TECHNOLOGY_DESCRIPTION = "TECHNOLOGY_DESCRIPTION"
    INSTALLATION = "INSTALLATION"
    USAGE = "USAGE"
    REQUIREMENTS = "REQUIREMENTS"
    INFRASTRUCTURE_DESCRIPTION = "INFRASTRUCTURE_DESCRIPTION"
    API_DESCRIPTION = "API_DESCRIPTION"
