spring.application.name=devlog-ai-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/devlog_ai
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username = devlog
spring.datasource.password= devlog
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


