package com.hopeful117.devlogai.contextmaintenance.entity;

public enum MaintenanceFindingIssueType {
    STALE_PROJECT_UNDERSTANDING,
    PROJECTION_REFRESH_GAP,
    MISSING_PROJECTION_REFRESH,
    STALE_HUMAN_CONTEXT_INPUT,
    TRUSTED_KNOWLEDGE_EXACT_DUPLICATE,
    TRUSTED_KNOWLEDGE_SEMANTIC_DUPLICATE,
    TRUSTED_KNOWLEDGE_OVERLAP_REVIEW
}
